In [1]:
list(range(2, 101, 2))

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [2]:
[num for num in range(1,101) if num % 2 == 0]

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [4]:
dic = {"MG": "Minas Gerais", "SP":"São Paulo", "AC":"Acre", "MA":"Maranhão"}
regioes = ["SE", "SE", "NO", "NE"]
estados = list(zip(dic, dic.values(), regioes))
estados

[('MG', 'Minas Gerais', 'SE'),
 ('SP', 'São Paulo', 'SE'),
 ('AC', 'Acre', 'NO'),
 ('MA', 'Maranhão', 'NE')]

In [6]:
bissextos = [ano for ano in range(1900, 2021, 4) if (ano % 400 == 0) or (ano % 4 == 0 and ano % 100 != 0)]
bissextos

[1904,
 1908,
 1912,
 1916,
 1920,
 1924,
 1928,
 1932,
 1936,
 1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

In [7]:
bissextos1 = list(filter(lambda ano: (ano % 400 == 0) or (ano % 4 == 0 and ano % 100 != 0), range(1900, 2021, 4)))
bissextos1

[1904,
 1908,
 1912,
 1916,
 1920,
 1924,
 1928,
 1932,
 1936,
 1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

In [8]:
bissextos == bissextos1

True

In [9]:
bissextos2 = list(range(1900, 2021, 4))
bissextos1 == bissextos2

False

In [2]:
import numpy as np
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [3]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [4]:
percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[::2]

array([0, 2, 4, 6, 8])

In [7]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [8]:
arr[-2::-2]

array([8, 6, 4, 2, 0])

In [9]:
arr = np.eye(5)

In [10]:
arr[arr == 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [11]:
arr[arr != 1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
arr - (np.eye(5) + 1)

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [20]:
from string import ascii_lowercase, ascii_uppercase

In [15]:
ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [21]:
[ascii_uppercase[x] for x in range(6)]

['A', 'B', 'C', 'D', 'E', 'F']

In [22]:
import pandas as pd

In [23]:
s = pd.Series([1, 2,3, 4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
s.shape

(5,)

In [25]:
np.array([1, 2,3, 4, 5]).shape

(5,)

In [26]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
df

0  1  2
0  1  2  3
1  4  5  6

In [27]:
df.shape

(2, 3)

In [28]:
nomes = ("Minas Gerais", "Amazonas", "Maranhão", "Goiás", "Santa Catarina")
siglas = ("MG", "AM", "MA", "GO", "SC")
estados = pd.Series(siglas, nomes)

In [29]:
estados

Minas Gerais      MG
Amazonas          AM
Maranhão          MA
Goiás             GO
Santa Catarina    SC
dtype: object